let foodDatabase = [
    {
        id: 1,
        name: "apple",
        color: "red",
        type: "fruit",
        origin: "China",
        nutrition: {carbohydrates: 14, protein: 0.3, fat: 0.2},
        benefit: "Packed with fiber that supports digestion and heart health.",
        story: "A medium apple gives you about 14% of your daily Vitamin C. The saying 'an apple a day keeps the doctor away' dates back to 1860s Wales.",
        menu: ["Apple Pie", "Applesauce", "Apple Cider", "Caramel Apple", "Apple Strudel"]
    },
    {
        id: 2,
        name: "banana",
        color: "yellow",
        type: "fruit",
        origin: "Ecuador",
        nutrition: {carbohydrates: 27, protein: 1.3, fat: 0.3},
        benefit: "Rich in potassium, perfect for muscle recovery and energy.",
        story: "Bananas are technically berries, but strawberries aren't! A cluster of bananas is called a 'hand'.",
        menu: ["Banana Bread", "Banana Smoothie", "Banana Pancakes", "Banana Split", "Bananas Foster"]
    },
    {
        id: 3,
        name: "carrot",
        color: "orange",
        type: "vegetable",
        origin: "Netherlands",
        nutrition: {carbohydrates: 10, protein: 0.9, fat: 0.1},
        benefit: "Loaded with beta-carotene for sharp vision and glowing skin.",
        story: "Carrots were originally purple and white. The orange carrot was developed in the Netherlands in the 17th century.",
        menu: ["Carrot Cake", "Carrot Soup", "Glazed Carrots", "Carrot Salad", "Carrot Juice"]
    },
    {
        id: 4,
        name: "date",
        color: "brown",
        type: "fruit",
        origin: "Iran",
        nutrition: {carbohydrates: 22, protein: 0.2, fat: 0.1},
        benefit: "A natural energy booster with fiber and essential minerals.",
        story: "Dates have been cultivated for over 6,000 years. They are one of the oldest cultivated fruits.",
        menu: ["Date Energy Balls", "Date Smoothie", "Stuffed Dates", "Date Bread", "Date Syrup"]
    },
    {
        id: 5,
        name: "eggplant",
        color: "purple",
        type: "vegetable",
        origin: "India",
        nutrition: {carbohydrates: 6, protein: 1, fat: 0.2},
        benefit: "Helps lower cholesterol with its powerful antioxidants.",
        story: "Eggplants are actually berries and were originally white and looked like eggs — hence the name!",
        menu: ["Eggplant Parmesan", "Baba Ganoush", "Ratatouille", "Grilled Eggplant", "Moussaka"]
    },
    {
        id: 6,
        name: "orange",
        color: "orange",
        type: "fruit",
        origin: "Brazil",
        nutrition: {carbohydrates: 12, protein: 0.9, fat: 0.1},
        benefit: "Packed with Vitamin C to strengthen your immune system.",
        story: "Oranges are a hybrid between pomelo and mandarin. Brazil grows about a third of the world's supply.",
        menu: ["Orange Juice", "Orange Marmalade", "Orange Chicken", "Orange Salad", "Orange Sorbet"]
    },
    {
        id: 7,
        name: "strawberry",
        color: "red",
        type: "fruit",
        origin: "Mexico",
        nutrition: {carbohydrates: 8, protein: 0.7, fat: 0.3},
        benefit: "Supports heart health with anti-inflammatory antioxidants.",
        story: "The average strawberry has about 200 tiny seeds on its surface. It's the only fruit with seeds on the outside!",
        menu: ["Strawberry Shortcake", "Strawberry Jam", "Strawberry Smoothie", "Chocolate-Covered Strawberries", "Strawberry Ice Cream"]
    },
    {
        id: 8,
        name: "watermelon",
        color: "green",
        type: "fruit",
        origin: "China",
        nutrition: {carbohydrates: 8, protein: 0.6, fat: 0.2},
        benefit: "Keeps you hydrated and supports healthy skin.",
        story: "Watermelon is 92% water — that's why it's named that way! The heaviest weighed over 159 kg.",
        menu: ["Watermelon Salad", "Watermelon Juice", "Grilled Watermelon", "Watermelon Sorbet", "Watermelon Agua Fresca"]
    },
    {
        id: 9,
        name: "pineapple",
        color: "yellow",
        type: "fruit",
        origin: "Costa Rica",
        nutrition: {carbohydrates: 13, protein: 0.5, fat: 0.1},
        benefit: "Contains bromelain enzyme that aids digestion.",
        story: "Pineapples take about two years to grow. They are a collection of many tiny fruits fused together.",
        menu: ["Pineapple Upside-Down Cake", "Pineapple Smoothie", "Grilled Pineapple", "Pineapple Fried Rice", "Pina Colada"]
    },
    {
        id: 10,
        name: "mango",
        color: "yellow",
        type: "fruit",
        origin: "India",
        nutrition: {carbohydrates: 15, protein: 0.8, fat: 0.4},
        benefit: "Boosts immunity with high levels of Vitamin A and C.",
        story: "Mango is the national fruit of India, Pakistan, and the Philippines. There are over 500 varieties.",
        menu: ["Mango Smoothie", "Mango Lassi", "Mango Salsa", "Mango Sticky Rice", "Mango Sorbet"]
    },
    {
        id: 11,
        name: "grape",
        color: "purple",
        type: "fruit",
        origin: "Italy",
        nutrition: {carbohydrates: 18, protein: 0.7, fat: 0.2},
        benefit: "Promotes heart health with antioxidants called polyphenols.",
        story: "It takes about 2.5 pounds of grapes to make a single bottle of wine. Grapes have been cultivated for 8,000 years.",
        menu: ["Grape Juice", "Grape Jelly", "Wine", "Grape Salad", "Frozen Grapes"]
    },
    {
        id: 12,
        name: "kiwi",
        color: "green",
        type: "fruit",
        origin: "New Zealand",
        nutrition: {carbohydrates: 15, protein: 1.1, fat: 0.5},
        benefit: "Packed with Vitamin C and supports better sleep.",
        story: "Kiwis are named after the kiwi bird, which is also native to New Zealand.",
        menu: ["Kiwi Smoothie", "Kiwi Sorbet", "Kiwi Fruit Salad", "Kiwi Jam", "Kiwi Yogurt Parfait"]
    },
    {
        id: 13,
        name: "lemon",
        color: "yellow",
        type: "fruit",
        origin: "Argentina",
        nutrition: {carbohydrates: 9, protein: 1.1, fat: 0.3},
        benefit: "Alkalizes the body and supports detoxification.",
        story: "Lemon trees can produce up to 1,500 lemons per year. The sourness comes from citric acid.",
        menu: ["Lemonade", "Lemon Bars", "Lemon Chicken", "Lemon Sorbet", "Lemon Meringue Pie"]
    },
    {
        id: 14,
        name: "cherry",
        color: "red",
        type: "fruit",
        origin: "Turkey",
        nutrition: {carbohydrates: 16, protein: 1, fat: 0.2},
        benefit: "Contains melatonin that may improve sleep quality.",
        story: "There are over 1,000 different varieties of cherries worldwide. Turkey is the largest producer.",
        menu: ["Cherry Pie", "Cherry Jam", "Chocolate-Covered Cherries", "Cherry Smoothie", "Black Forest Cake"]
    },
    {
        id: 15,
        name: "peach",
        color: "orange",
        type: "fruit",
        origin: "China",
        nutrition: {carbohydrates: 10, protein: 0.9, fat: 0.3},
        benefit: "Rich in Vitamin C for collagen production and immunity.",
        story: "Peaches are a member of the rose family, along with plums, apricots, and cherries.",
        menu: ["Peach Cobbler", "Peach Jam", "Grilled Peaches", "Peach Smoothie", "Peach Salsa"]
    },
    {
        id: 16,
        name: "pear",
        color: "yellow",
        type: "fruit",
        origin: "China",
        nutrition: {carbohydrates: 15, protein: 0.4, fat: 0.1},
        benefit: "High in fiber, great for digestive regularity.",
        story: "Pears are one of the few fruits that ripen better off the tree.",
        menu: ["Poached Pears", "Pear Tart", "Pear Salad", "Pear Butter", "Pear Crumble"]
    },
    {
        id: 17,
        name: "blueberry",
        color: "blue",
        type: "fruit",
        origin: "USA",
        nutrition: {carbohydrates: 14, protein: 0.7, fat: 0.3},
        benefit: "Known to boost brain function and delay cognitive decline.",
        story: "Blueberries are one of the only naturally blue foods, thanks to anthocyanin antioxidants.",
        menu: ["Blueberry Muffins", "Blueberry Pancakes", "Blueberry Smoothie", "Blueberry Pie", "Blueberry Jam"]
    },
    {
        id: 18,
        name: "pomegranate",
        color: "red",
        type: "fruit",
        origin: "Iran",
        nutrition: {carbohydrates: 19, protein: 1.7, fat: 1.2},
        benefit: "Powerful antioxidants that support heart health.",
        story: "A single pomegranate can contain up to 600 seeds. In Greek mythology, it was the 'fruit of the dead'.",
        menu: ["Pomegranate Juice", "Pomegranate Salad", "Pomegranate Molasses", "Pomegranate Smoothie", "Pomegranate Sorbet"]
    },
    {
        id: 19,
        name: "coconut",
        color: "brown",
        type: "fruit",
        origin: "Indonesia",
        nutrition: {carbohydrates: 15, protein: 3.3, fat: 33},
        benefit: "Provides medium-chain fats for quick energy.",
        story: "Coconuts are not nuts — they are drupes. Coconut water was used in WWII medical emergencies.",
        menu: ["Coconut Curry", "Coconut Rice", "Coconut Macaroons", "Coconut Milk Smoothie", "Coconut Shrimp"]
    },
    {
        id: 20,
        name: "tomato",
        color: "red",
        type: "vegetable",
        origin: "Italy",
        nutrition: {carbohydrates: 4, protein: 0.9, fat: 0.2},
        benefit: "Rich in lycopene that supports prostate health.",
        story: "Botanically a fruit, but legally a vegetable! The US Supreme Court ruled on this in 1893.",
        menu: ["Tomato Soup", "Tomato Sauce", "Caprese Salad", "Tomato Juice", "Ketchup"]
    },
    {
        id: 21,
        name: "cucumber",
        color: "green",
        type: "vegetable",
        origin: "China",
        nutrition: {carbohydrates: 4, protein: 0.7, fat: 0.1},
        benefit: "Hydrates and soothes skin with natural silica content.",
        story: "Cucumbers are 96% water, making them the most hydrating snack you can eat.",
        menu: ["Cucumber Salad", "Cucumber Water", "Cucumber Sandwiches", "Tzatziki Sauce", "Pickles"]
    },
    {
        id: 22,
        name: "broccoli",
        color: "green",
        type: "vegetable",
        origin: "China",
        nutrition: {carbohydrates: 7, protein: 2.8, fat: 0.4},
        benefit: "Packed with sulforaphane that may help fight cancer.",
        story: "Broccoli has more protein than beef per calorie and more Vitamin C than an orange, gram for gram.",
        menu: ["Broccoli Cheddar Soup", "Roasted Broccoli", "Broccoli Salad", "Stir-Fried Broccoli", "Broccoli Quiche"]
    },
    {
        id: 23,
        name: "bell pepper",
        color: "red",
        type: "vegetable",
        origin: "Mexico",
        nutrition: {carbohydrates: 6, protein: 1, fat: 0.3},
        benefit: "Rich in Vitamin C — more than an orange!",
        story: "Bell peppers are the only peppers that don't produce capsaicin. Red ones are just ripe green ones!",
        menu: ["Stuffed Bell Peppers", "Roasted Red Pepper Soup", "Bell Pepper Stir-Fry", "Fajitas", "Pepper Salad"]
    },
    {
        id: 24,
        name: "onion",
        color: "white",
        type: "vegetable",
        origin: "India",
        nutrition: {carbohydrates: 9, protein: 1.1, fat: 0.1},
        benefit: "Contains quercetin that supports heart health.",
        story: "Onion layers can be used to make natural golden-brown dye. The chemical that makes you cry dissipates when cooked.",
        menu: ["French Onion Soup", "Caramelized Onions", "Onion Rings", "Onion Dip", "Pickled Onions"]
    },
    {
        id: 25,
        name: "mushroom",
        color: "brown",
        type: "vegetable",
        origin: "China",
        nutrition: {carbohydrates: 3, protein: 3.1, fat: 0.3},
        benefit: "One of the few natural sources of Vitamin D.",
        story: "Mushrooms are fungi, not plants, and can produce Vitamin D when exposed to sunlight — just like humans!",
        menu: ["Mushroom Risotto", "Stuffed Mushrooms", "Mushroom Soup", "Grilled Mushrooms", "Mushroom Pasta"]
    },
    {
        id: 26,
        name: "corn",
        color: "yellow",
        type: "vegetable",
        origin: "USA",
        nutrition: {carbohydrates: 19, protein: 3.4, fat: 1.2},
        benefit: "Provides fiber and B vitamins for energy metabolism.",
        story: "An ear of corn always has an even number of rows, typically 16. It was domesticated in Mexico 9,000 years ago.",
        menu: ["Corn on the Cob", "Popcorn", "Cornbread", "Corn Chowder", "Grilled Corn Salad"]
    },
    {
        id: 27,
        name: "spinach",
        color: "green",
        type: "vegetable",
        origin: "China",
        nutrition: {carbohydrates: 4, protein: 2.9, fat: 0.4},
        benefit: "Rich in iron for healthy blood and oxygen transport.",
        story: "Popeye made spinach famous — US spinach sales increased by 33% after the cartoon aired!",
        menu: ["Spinach Salad", "Creamed Spinach", "Spinach Dip", "Spinach Quiche", "Sauteed Spinach"]
    },
    {
        id: 28,
        name: "potato",
        color: "brown",
        type: "vegetable",
        origin: "China",
        nutrition: {carbohydrates: 17, protein: 2, fat: 0.1},
        benefit: "A great source of potassium that supports nerve function.",
        story: "Potatoes were the first vegetable grown in space, aboard the Space Shuttle Columbia in 1995.",
        menu: ["French Fries", "Mashed Potatoes", "Baked Potato", "Potato Salad", "Potato Soup"]
    },
    {
        id: 29,
        name: "avocado",
        color: "green",
        type: "fruit",
        origin: "Mexico",
        nutrition: {carbohydrates: 9, protein: 2, fat: 15},
        benefit: "Packed with healthy monounsaturated fats that support heart health.",
        story: "Avocados are berries with a single seed. The name comes from the Aztec word 'ahuacatl' meaning 'testicle'.",
        menu: ["Guacamole", "Avocado Toast", "Avocado Salad", "Avocado Smoothie", "Avocado Sushi"]
    },
    {
        id: 30,
        name: "raspberry",
        color: "red",
        type: "fruit",
        origin: "Russia",
        nutrition: {carbohydrates: 12, protein: 1.2, fat: 0.7},
        benefit: "Rich in antioxidants that help fight inflammation and aging.",
        story: "Raspberries were used as a natural red dye in ancient times. They belong to the rose family.",
        menu: ["Raspberry Jam", "Raspberry Smoothie", "Raspberry Tart", "Raspberry Sauce", "Raspberry Muffins"]
    },
    {
        id: 31,
        name: "blackberry",
        color: "black",
        type: "fruit",
        origin: "USA",
        nutrition: {carbohydrates: 10, protein: 1.4, fat: 0.5},
        benefit: "High in Vitamin C and fiber, great for digestive health.",
        story: "A blackberry is not a single fruit — each one is a cluster of tiny fruits called drupelets.",
        menu: ["Blackberry Cobbler", "Blackberry Jam", "Blackberry Smoothie", "Blackberry Pie", "Blackberry Sauce"]
    },
    {
        id: 32,
        name: "apricot",
        color: "orange",
        type: "fruit",
        origin: "Turkey",
        nutrition: {carbohydrates: 11, protein: 1.4, fat: 0.4},
        benefit: "Loaded with beta-carotene for healthy skin and eyes.",
        story: "Apricots have been cultivated in Armenia for over 3,000 years. The scientific name means 'Armenian plum'.",
        menu: ["Apricot Jam", "Dried Apricots", "Apricot Tart", "Apricot Chicken", "Apricot Smoothie"]
    },
    {
        id: 33,
        name: "plum",
        color: "purple",
        type: "fruit",
        origin: "China",
        nutrition: {carbohydrates: 11, protein: 0.7, fat: 0.3},
        benefit: "Contains antioxidants that may improve memory and brain function.",
        story: "There are over 2,000 varieties of plums. Dried plums are called prunes.",
        menu: ["Plum Tart", "Plum Jam", "Plum Sauce", "Poached Plums", "Plum Crumble"]
    },
    {
        id: 34,
        name: "fig",
        color: "purple",
        type: "fruit",
        origin: "Turkey",
        nutrition: {carbohydrates: 19, protein: 0.8, fat: 0.3},
        benefit: "A great source of calcium for bone health.",
        story: "Figs are not actually fruits — they are inverted flowers that bloom inside the pod!",
        menu: ["Fig Jam", "Fig Newtons", "Fig Salad", "Stuffed Figs", "Fig Tart"]
    },
    {
        id: 35,
        name: "grapefruit",
        color: "pink",
        type: "fruit",
        origin: "USA",
        nutrition: {carbohydrates: 11, protein: 0.8, fat: 0.1},
        benefit: "Can help boost metabolism and support weight loss.",
        story: "Grapefruit is a hybrid of pomelo and orange, first discovered in Barbados in the 18th century.",
        menu: ["Grapefruit Juice", "Broiled Grapefruit", "Grapefruit Salad", "Grapefruit Sorbet", "Grapefruit Marmalade"]
    },
    {
        id: 36,
        name: "passion fruit",
        color: "purple",
        type: "fruit",
        origin: "Brazil",
        nutrition: {carbohydrates: 23, protein: 2.2, fat: 0.7},
        benefit: "Rich in Vitamin A and C, supports healthy skin.",
        story: "The name comes from Spanish missionaries who saw the flower as a symbol of the crucifixion story.",
        menu: ["Passion Fruit Juice", "Passion Fruit Mousse", "Passion Fruit Sauce", "Passion Fruit Smoothie", "Passion Fruit Sorbet"]
    },
    {
        id: 37,
        name: "papaya",
        color: "orange",
        type: "fruit",
        origin: "Mexico",
        nutrition: {carbohydrates: 11, protein: 0.5, fat: 0.3},
        benefit: "Contains papain enzyme that aids digestion.",
        story: "Papaya trees can grow up to 30 feet tall and produce fruit year-round.",
        menu: ["Papaya Smoothie", "Papaya Salad", "Papaya Sorbet", "Dried Papaya", "Papaya Boat"]
    },
    {
        id: 38,
        name: "guava",
        color: "green",
        type: "fruit",
        origin: "India",
        nutrition: {carbohydrates: 14, protein: 2.6, fat: 1},
        benefit: "Packed with 4x more Vitamin C than an orange.",
        story: "Guava trees are so hardy they can grow in volcanic soil and drought conditions.",
        menu: ["Guava Juice", "Guava Paste", "Guava Smoothie", "Guava Jam", "Guava Cheesecake"]
    },
    {
        id: 39,
        name: "lychee",
        color: "red",
        type: "fruit",
        origin: "China",
        nutrition: {carbohydrates: 17, protein: 0.8, fat: 0.4},
        benefit: "Rich in copper which supports red blood cell production.",
        story: "Lychee was so prized in ancient China that emperors had them rushed by horseback from the south.",
        menu: ["Lychee Smoothie", "Lychee Sorbet", "Lychee Cocktail", "Lychee Salad", "Lychee Ice Cream"]
    },
    {
        id: 40,
        name: "cranberry",
        color: "red",
        type: "fruit",
        origin: "USA",
        nutrition: {carbohydrates: 12, protein: 0.4, fat: 0.1},
        benefit: "Known for preventing urinary tract infections.",
        story: "Fresh cranberries bounce when dropped — that's how farmers test their quality!",
        menu: ["Cranberry Sauce", "Cranberry Juice", "Dried Cranberries", "Cranberry Muffins", "Cranberry Relish"]
    },
    {
        id: 41,
        name: "nectarine",
        color: "red",
        type: "fruit",
        origin: "USA",
        nutrition: {carbohydrates: 11, protein: 1.1, fat: 0.3},
        benefit: "High in fiber and Vitamin A for healthy vision.",
        story: "Nectarines are peaches without the fuzz — a natural genetic mutation, not a hybrid.",
        menu: ["Nectarine Tart", "Grilled Nectarines", "Nectarine Salsa", "Nectarine Smoothie", "Nectarine Jam"]
    },
    {
        id: 42,
        name: "persimmon",
        color: "orange",
        type: "fruit",
        origin: "China",
        nutrition: {carbohydrates: 18, protein: 0.6, fat: 0.2},
        benefit: "Loaded with Vitamin A and manganese for eye health.",
        story: "Persimmons were known as the 'fruit of the gods' in ancient Greece.",
        menu: ["Persimmon Bread", "Persimmon Salad", "Dried Persimmons", "Persimmon Smoothie", "Persimmon Pudding"]
    },
    {
        id: 43,
        name: "dragon fruit",
        color: "pink",
        type: "fruit",
        origin: "Vietnam",
        nutrition: {carbohydrates: 9, protein: 1.1, fat: 0.4},
        benefit: "Contains prebiotics that support gut health.",
        story: "Dragon fruit comes from a type of cactus that blooms only at night, with flowers that last just one night.",
        menu: ["Dragon Fruit Smoothie", "Dragon Fruit Bowl", "Dragon Fruit Sorbet", "Dragon Fruit Salad", "Dragon Fruit Juice"]
    },
    {
        id: 44,
        name: "star fruit",
        color: "yellow",
        type: "fruit",
        origin: "Malaysia",
        nutrition: {carbohydrates: 7, protein: 0.4, fat: 0.3},
        benefit: "Low in calories and packed with Vitamin C.",
        story: "When sliced crosswise, star fruit forms perfect five-pointed stars — hence the name.",
        menu: ["Star Fruit Juice", "Star Fruit Salad", "Star Fruit Chutney", "Star Fruit Smoothie", "Candied Star Fruit"]
    },
    {
        id: 45,
        name: "boysenberry",
        color: "purple",
        type: "fruit",
        origin: "USA",
        nutrition: {carbohydrates: 12, protein: 1.4, fat: 0.5},
        benefit: "Rich in fiber and folate for heart health.",
        story: "Boysenberries are a hybrid of raspberry, blackberry, and loganberry, created by Rudolph Boysen in the 1920s.",
        menu: ["Boysenberry Pie", "Boysenberry Jam", "Boysenberry Smoothie", "Boysenberry Syrup", "Boysenberry Crumble"]
    },
    {
        id: 46,
        name: "tangerine",
        color: "orange",
        type: "fruit",
        origin: "China",
        nutrition: {carbohydrates: 13, protein: 0.8, fat: 0.3},
        benefit: "Boosts immunity with high levels of Vitamin C.",
        story: "Tangerines were named after Tangier, Morocco, where they were first shipped to Europe.",
        menu: ["Tangerine Juice", "Tangerine Salad", "Tangerine Sorbet", "Candied Tangerines", "Tangerine Marmalade"]
    },
    {
        id: 47,
        name: "honeydew",
        color: "green",
        type: "fruit",
        origin: "China",
        nutrition: {carbohydrates: 9, protein: 0.5, fat: 0.1},
        benefit: "Hydrating and rich in Vitamin C and potassium.",
        story: "Honeydew melons are named for their sweet, honey-like flavor when fully ripe.",
        menu: ["Honeydew Smoothie", "Honeydew Salad", "Honeydew Sorbet", "Honeydew Agua Fresca", "Honeydew Fruit Bowl"]
    },
    {
        id: 48,
        name: "cantaloupe",
        color: "orange",
        type: "fruit",
        origin: "China",
        nutrition: {carbohydrates: 8, protein: 0.8, fat: 0.2},
        benefit: "Excellent source of Vitamin A for eye health.",
        story: "Cantaloupes are named after the papal gardens of Cantalupo in Italy, where they were first grown in Europe.",
        menu: ["Cantaloupe Smoothie", "Cantaloupe Salad", "Cantaloupe Sorbet", "Grilled Cantaloupe", "Cantaloupe Prosciutto"]
    },
    {
        id: 49,
        name: "jackfruit",
        color: "yellow",
        type: "fruit",
        origin: "India",
        nutrition: {carbohydrates: 23, protein: 1.4, fat: 0.6},
        benefit: "Contains potassium that helps regulate blood pressure.",
        story: "Jackfruit is the largest tree fruit in the world, weighing up to 40 kg (88 lbs)!",
        menu: ["Jackfruit Curry", "BBQ Jackfruit", "Jackfruit Chips", "Jackfruit Smoothie", "Jackfruit Tacos"]
    },
    {
        id: 50,
        name: "plantain",
        color: "yellow",
        type: "vegetable",
        origin: "Colombia",
        nutrition: {carbohydrates: 32, protein: 1.3, fat: 0.4},
        benefit: "A great source of complex carbohydrates for sustained energy.",
        story: "Plantains look like bananas but are starchier and must be cooked before eating.",
        menu: ["Fried Plantains", "Plantain Chips", "Mofongo", "Plantain Soup", "Baked Plantains"]
    }
];
